export const TEAM_LOGOS: Record<string, string> = {
  UF: "/team-logos/florida.svg",
  UT: "/team-logos/texas.svg",
  USC: "/team-logos/usc.svg",
  LSU: "/team-logos/lsu.svg",
  UO: "/team-logos/oregon.svg",
  UGA: "/team-logos/georgia.svg",
  ARK: "/team-logos/arkansas.png",
  UCLA: "/team-logos/ucla.svg",
  UNC: "/team-logos/north-carolina.svg",
  TAMU: "/team-logos/texas-am.png",
  ALA: "/team-logos/alabama.svg",
  AUB: "/team-logos/auburn.svg",
  UK: "/team-logos/kentucky.svg",
  TENN: "/team-logos/tennessee.svg",
  SC: "/team-logos/south-carolina.svg",
  OSU: "/team-logos/ohio-state.svg",
  MICH: "/team-logos/michigan.svg",
  BAY: "/team-logos/baylor.svg",
  HOU: "/team-logos/houston.svg",
  CLEM: "/team-logos/clemson.svg",
  FSU: "/team-logos/florida-state.svg",
  MIA: "/team-logos/miami.svg",
  ASU: "/team-logos/arizona-state.svg",
  TCU: "/team-logos/tcu.svg",
};
